### ISSUE TITLE
Add usage documentation

### ISSUE THREAD

**Issue by dirx** [idealo/php-rdkafka-ffi#12]
- [ ] Consumer low level
- [ ] Consumer high level
- [ ] Producer
- [ ] Configuration
- [ ] Topic Configuration
- [ ] Admin Client
- [ ] Mock Cluster
- [ ] librdkafka Version Handling
- [ ] FFI and librdkafka
- [ ] Preload

**Comment by manonworld** [comment]
I am working on it :) if you do not mind
