### ISSUE TITLE
Do Message payload support binary data?

### ISSUE THREAD

**Issue by signalarun** [idealo/php-rdkafka-ffi#16]

**Comment by dirx** [comment]
Hi @signalarun, roughly one year later ...

Message payload does support binary data. 

Payload data and payload (bytes) length are always handled separately.
When producing a message the binary safe PHP string type and  `strlen` is used to detect the payload length.
When consuming a message its payload length is is used to write the payload data into a PHP string.

Plus: librdkafka / kafka can handle binary payload data of the box. See: https://github.com/confluentinc/librdkafka/issues/2515

A common use case for binary payload data is Avro serialization.

The message key is handled the same way. The key length itself is not exposed via the Message interface. To detect the length use `strlen` on the message key  property.
