### ISSUE TITLE
Question: Benchmark

### ISSUE THREAD

**Issue by nick-zh** [idealo/php-rdkafka-ffi#6]
Hey @dirx 

Cool project, i will check it out on the weekend :+1:
I was actually about to do the same :smile:  
Out of curiosity, have you done some inital benchmarking against the extension?
I am very interested in how this roughly compares (probably others are too).

Cheers,
Nick

**Comment by dirx** [comment]
@nick-zh Thank you!

Yes - benchmarking would be nice - just thought about this yesterday when working on one docker file for ffi & rdkafka ext for testing: should also be a good start for benchmarking ... 

Just played around with phpbench - first simple Producer benchmarks:

| benchmark     | subject                 | set | revs | tag:ffi:mean | tag:ext:mean |
|---------------|-------------------------|-----|------|--------------|--------------|
| ProducerBench | benchProduce1Message    | 0   | 1000 | 2,091.712μs  | 2,041.982μs  |
| ProducerBench | benchProduce100Messages | 0   | 100  | 2,097.398μs  | 2,018.376μs  |

See the [readme](https://github.com/dirx/php-ffi-librdkafka#run-benchmarks) for more details on how to re-play.

**Comment by nick-zh** [comment]
Awesome thx for the insight @dirx
